version: '3.9'

services:

  vault:
    build:
      context: .
      dockerfile: DockerfileVault
    container_name: vault-server
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: ${VAULT_ADDR}
      VAULT_SKIP_VERIFY: true
    volumes:
      - ./vault/data:/vault/file
      - ./vault/logs:/vault/logs
      - ./configVault:/vault/config:rw
      - ./vault/keys:/vault/keys
      - ./vault/ssl:/vault/ssl
      - ./.env:/vault/.env
    command: vault server -config=/vault/config/config.hcl
    cap_add:
      - IPC_LOCK
    networks:
      - flink-network

  init-db-ssl:
    image: busybox
    volumes:
      - ./vault/ssl/postgres-server:/var/lib/postgresql/certs/
      - ./vault/ssl/postgres-client-keycloak:/var/lib/postgresql-client/certs/
    command: sh -c "
      chown -R 999:999 /var/lib/postgresql/certs &&
      chmod 600 /var/lib/postgresql/certs/server.key &&
      chmod 644 /var/lib/postgresql/certs/server.crt &&
      chmod 644 /var/lib/postgresql/certs/ca.crt"
    depends_on:
      - postgres

  init-container-ssl:
    image: busybox
    depends_on:
      - init-db
      - minio
      - keycloak
      - monitoring-api
      - flink_load
      - file-acceptor
      - frontend
      - nginx



  nginx:
    image: openresty/openresty:latest
    container_name: nginx-ssl-proxy
    depends_on:
      - frontend
      - keycloak
      - monitoring-api
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/:/etc/ssl:ro
    ports:
      - "80:80"
      - "443:443"
      - "8081:8081"
      - "9999:9999"
      - "62049:62049"
      - "9001:9001"
    networks:
      - flink-network


  postgres:
    build:
      context: .
      dockerfile: DockerfilePostgres
    container_name: postgres-bitdive
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgresql:/var/lib/postgresql/data
      - ./postgresConfig/postgres-init:/docker-entrypoint-initdb.d
      - ./postgresConfig/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./postgresConfig/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./vault/ssl/postgres-server:/var/lib/postgresql/certs/
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    command: >
      postgres 
       -c config_file=/etc/postgresql/postgresql.conf
       && pg_ctl reload
    restart: unless-stopped
    networks:
      - flink-network

  minio:
    image: minio/minio:RELEASE.2024-10-02T17-50-41Z
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_DOMAIN: ${MINIO_DOMAIN}
    volumes:
      - ./minio/data:/data
    command: server --console-address "${MINIO_CONSOLE_ADDRESS}" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - flink-network

  keycloak:
    image: keycloak/keycloak:26.0
    container_name: keycloak
    restart: unless-stopped
    volumes:
      - ./vault/ssl/postgres-client-keycloak/keystore.jks:/etc/keycloak/postgres-keystore.jks
      - ./vault/ssl/postgres-client-keycloak/truststore.jks:/etc/keycloak/postgres-truststore.jks
      - ./vault/ssl/keycloak-https/keystore.jks:/etc/keycloak/https-keystore.jks
      - ./vault/ssl/keycloak-https/truststore.jks:/etc/keycloak/https-truststore.jks
    environment:
      KC_DB: postgres
      KC_DB_URL: ${KEYCLOAK_DB_URL}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USERNAME}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_HOSTNAME: keycloak
      KC_PROXY_HEADERS: xforwarded
      KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: "${KEYCLOAK_HTTP_ENABLED}"
      KC_HTTP_SSL_PORT: "${KEYCLOAK_HTTP_SSL_PORT}"
      KC_HTTPS_KEY_STORE_FILE: "/etc/keycloak/https-keystore.jks"
      KC_HTTPS_KEY_STORE_PASSWORD: "${KEYCLOAK_KEY_STORE_PASSWORD}"
      JAVA_OPTS_APPEND: "-Djavax.net.ssl.keyStore=/etc/keycloak/postgres-keystore.jks -Djavax.net.ssl.keyStorePassword=${JAVA_KEYSTORE_PASSWORD} -Djavax.net.ssl.trustStore=/etc/keycloak/postgres-truststore.jks -Djavax.net.ssl.trustStorePassword=${JAVA_TRUSTSTORE_PASSWORD}"
    networks:
      - flink-network
    command: [ "start" ]


  init-db:
    image: frolikoveabitdive/bitdive-db-liquibase:0.0.1
    container_name: bitdive-init-db
    environment:
      POSTGRES_URL: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASS: ${POSTGRES_PASSWORD}

      VAULT_URL: ${VAULT_ADDR_CONTAINER}
      VAULT_LOGIN: ${VAULT_LOGIN}
      VAULT_PASSWORD: ${VAULT_PASSWORD}

      VAULT_CERTIFICATION_DB_COMMON_NAME: ${VAULT_CERT_DB_COMMON_NAME}
      VAULT_CERTIFICATION_DB_ALT_NAME: ${VAULT_CERT_DB_ALT_NAME}
      VAULT_CERTIFICATION_DB_TTL: ${VAULT_CERT_DB_TTL}
    networks:
      - flink-network

  monitoring-api:
    image: frolikoveabitdive/bitdive-monitoring-api:0.0.1
    container_name: monitoring-api
    environment:
      POSTGRES_URL: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASS: ${POSTGRES_PASSWORD}

      VAULT_URL: ${VAULT_ADDR_CONTAINER}
      VAULT_LOGIN: ${VAULT_LOGIN}
      VAULT_PASSWORD: ${VAULT_PASSWORD}

      VAULT_CERTIFICATION_DB_COMMON_NAME: ${VAULT_CERT_DB_COMMON_NAME}
      VAULT_CERTIFICATION_DB_ALT_NAME: ${VAULT_CERT_DB_ALT_NAME}
      VAULT_CERTIFICATION_DB_TTL: ${VAULT_CERT_DB_TTL}

      VAULT_CERTIFICATION_SERVICE_COMMON_NAME: ${VAULT_CERT_SERVICE_COMMON_NAME}
      VAULT_CERTIFICATION_SERVICE_ACCEPTOR_ALT_NAMES: ${VAULT_CERT_SERVICE_ALT_NAMES}
      VAULT_CERTIFICATION_SERVICE_ACCEPTOR_TTL: ${VAULT_CERT_SERVICE_TTL}

      VAULT_CERTIFICATION_KEY_CLOAK_COMMON_NAME: ${VAULT_CERT_KEYCLOAK_COMMON_NAME}
      VAULT_CERTIFICATION_KEY_CLOAK_ALT_NAME: ${VAULT_CERT_KEYCLOAK_ALT_NAME}
      VAULT_CERTIFICATION_KEY_CLOAK_TTL: ${VAULT_CERT_KEYCLOAK_TTL}

      URL_FRONT_SYSTEM: ${URL_FRONT_SYSTEM}

      KEY_CLOAK_URL: ${KEYCLOAK_REALM_URL}
      SERVICE_ENABLE_SLL_CONNECT: true
    restart: unless-stopped
    networks:
      - flink-network


  flink_load:
    image: frolikoveabitdive/bitdive-flink-write-minio:0.0.1
    container_name: flink_load_minio
    restart: unless-stopped
    environment:
      MINIO_USER: ${MINIO_ROOT_USER}
      MINIO_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_END_POINT: ${MINIO_ENDPOINT}
      POSTGRES_URL: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASS: ${POSTGRES_PASSWORD}
      VAULT_URL: ${VAULT_ADDR_CONTAINER}
      VAULT_LOGIN: ${VAULT_LOGIN}
      VAULT_PASSWORD: ${VAULT_PASSWORD}
      VAULT_CERTIFICATION_DB_COMMON_NAME: ${VAULT_CERT_DB_COMMON_NAME}
      VAULT_CERTIFICATION_DB_ALT_NAME: ${VAULT_CERT_DB_ALT_NAME}
      VAULT_CERTIFICATION_DB_TTL: ${VAULT_CERT_DB_TTL}
    depends_on:
      - minio
    networks:
      - flink-network


  file-acceptor:
    image: frolikoveabitdive/bitdive-file-acceptor:0.0.1
    container_name: file-acceptor
    restart: unless-stopped
    environment:
      MINIO_USER: ${MINIO_ROOT_USER}
      MINIO_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_END_POINT: ${MINIO_ENDPOINT}
      VAULT_URL: ${VAULT_ADDR_CONTAINER}
      VAULT_LOGIN: ${VAULT_LOGIN}
      VAULT_PASSWORD: ${VAULT_PASSWORD}
      VAULT_CERTIFICATION_SERVICE_COMMON_NAME: ${VAULT_CERT_SERVICE_COMMON_NAME}
      VAULT_CERTIFICATION_SERVICE_ACCEPTOR_ALT_NAMES: ${VAULT_CERT_SERVICE_ALT_NAMES}
      VAULT_CERTIFICATION_SERVICE_ACCEPTOR_TTL: ${VAULT_CERT_SERVICE_TTL}
      VAULT_CERTIFICATION_SERVICE_ACCEPTOR_IP_SANS: ${SERVER_IP}
    ports:
      - "8082:8082"
    depends_on:
      - minio
    networks:
      - flink-network

  frontend:
    image: frolikoveabitdive/bitdive-front:0.0.1
    container_name: frontend
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}
      REACT_APP_KEYCLOAK_URL: ${REACT_APP_KEYCLOAK_URL}
      REACT_APP_KEYCLOAK_REALM: ${REACT_APP_KEYCLOAK_REALM}
      REACT_APP_KEYCLOAK_CLIENT_ID: ${REACT_APP_KEYCLOAK_CLIENT_ID}
      GENERATE_SOURCEMAP: ${GENERATE_SOURCEMAP}
    restart: unless-stopped
    networks:
      - flink-network

networks:
  flink-network:
    driver: bridge