# pg_hba.conf

# Type  Database    User      Address                 Method
# Allow connections via SSL with certificate verification
hostssl  keycloak  citizix_user  keycloak.docker-compose_flink-network  scram-sha-256
host  data-bitdive citizix_user ::1/128 trust
host    data-bitdive    clickhouse_user    clickhouse-bitdive.docker-compose_flink-network    password
host    data-bitdive    clickhouse_user    bitdive-init-db-clickhouse.docker-compose_flink-network    password
hostssl    all    all    0.0.0.0/0               cert clientcert=verify-full
hostssl    all    all    ::/0                    cert clientcert=verify-full
local   replication     all                                     trust
local   all             all                                     trust
# Allow internal connections without client certificate


# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
#local   all             all                                     trust
# IPv4 local connections:
#host    all             all             127.0.0.1/32            trust
# IPv6 local connections:
#host    all             all             ::1/128                 trust
# Allow replication connections from localhost, by a user with the
# replication privilege.
#local   replication     all                                     trust
#host    replication     all             127.0.0.1/32            trust
#host    replication     all             ::1/128                 trust