# pg_hba.conf

# Тип  База данных    Пользователь      Адрес                 Метод
# Разрешить подключения через SSL с проверкой сертификата
host  data-bitdive citizix_user ::1/128 trust
host    data-bitdive    clickhouse_user    172.18.0.0/16    password
hostssl    all    all    0.0.0.0/0               cert clientcert=verify-full
hostssl    all    all    ::/0                    cert clientcert=verify-full
local   replication     all                                     trust
local   all             all                                     trust
# Разрешить внутренние подключения без клиентского сертификата


# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
#local   all             all                                     trust
# IPv4 local connections:
#host    all             all             127.0.0.1/32            trust
# IPv6 local connections:
#host    all             all             ::1/128                 trust
# Allow replication connections from localhost, by a user with the
# replication privilege.
#local   replication     all                                     trust
#host    replication     all             127.0.0.1/32            trust
#host    replication     all             ::1/128                 trust